# Generated by Django 5.0.3 on 2024-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_manual_car_is_automatic_alter_brand_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
    ]
