# Generated by Django 5.0.3 on 2024-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
