# Generated by Django 5.0.3 on 2024-03-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='renter',
            new_name='owner',
        ),
    ]
